version: "3.9"
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=scholarsome"
    restart: always
  scholarsome:
    image: scholarsome
    ports:
      - "3333:3333"
    environment:
      - "DATABASE_URL=mysql://root:${DB_PASSWORD}@db:3306/scholarsome"
      - "JWT_TOKEN=${JWT_TOKEN}"
      - "SMTP_HOST=${SMTP_HOST}"
      - "SMTP_PORT=${SMTP_PORT}"
      - "SMTP_USERNAME=${SMTP_USERNAME}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
    depends_on:
      - "db"
    restart: always
