version: "3.9"
services:
  redis:
    image: redis
    expose:
      - "6379:6379"
    command: "redis-server --save 20 1 --requirepass ${DATABASE_PASSWORD}"
    volumes:
      - redis:/data
    restart: always
  mariadb:
    image: mariadb
    expose:
      - "3306:3306"
    environment:
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MARIADB_ROOT_HOST=localhost"
      - "MARIADB_DATABASE=scholarsome"
      - "MARIADB_USER=scholarsome"
      - "MARIADB_PASSWORD=${DATABASE_PASSWORD}"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  scholarsome:
    image: hwgilbert16/scholarsome
    ports:
      - "${HTTP_PORT}:8080"
    environment:
      - "NODE_ENV=${NODE_ENV}"
      - "DATABASE_URL=mysql://scholarsome:${DATABASE_PASSWORD}@mariadb:3306/scholarsome"
      - "JWT_SECRET=${JWT_SECRET}"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_USERNAME="
      - "REDIS_PASSWORD=${DATABASE_PASSWORD}"
      - "SMTP_HOST=${SMTP_HOST}"
      - "SMTP_PORT=${SMTP_PORT}"
      - "SMTP_USERNAME=${SMTP_USERNAME}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
      - "HOST=${HOST}"
      - "SSL_KEY_BASE64=${SSL_KEY_BASE64}"
      - "SSL_CERT_BASE64=${SSL_CERT_BASE64}"
      - "SCHOLARSOME_RECAPTCHA_SITE=${RECAPTCHA_SITE}"
      - "SCHOLARSOME_RECAPTCHA_SECRET=${RECAPTCHA_SECRET}"
    depends_on:
      - "mariadb"
      - "redis"
    restart: always
volumes:
  redis:
    driver: local
  mariadb:
