name: Build test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/Hydrogen'

      - name: npm install and prisma generate
        run: |
          npm install --legacy-peer-deps
          npm run generate
          npm run setEnv

      - name: Nx build and lint
        run: |
          npm run build
          npm run lint

