name: Run tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/Hydrogen'

      - name: Install dependencies and run migrations
        run: |
          npm install --legacy-peer-deps
          npm run generate

      - name: Build website and lint
        run: |
          npm run build
          npm run lint

      - name: Build docs
        run: npx nx build docs --skip-nx-cache

      - name: Run tests
        run: npx nx test api

